{% set name = "lb-nightly-db" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lb-nightly-db-{{ version }}.tar.gz
  sha256: fbc7e9144bf0f27d4e74055130959dd408b37b1de4effa63d7d4826a486df3d6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - cloudant >=2.14.0,<3.0.0
    - lb-nightly-configuration >=0.3,<1.0
    - python >={{ python_min }},<4.0

test:
  imports:
    - lb
    - lb.nightly.db
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/lb-nightly-db/
  summary: Database access layer for LHCb Nightly and Continuous Integration Build System
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pikacic
    - maszyman
